//
// Created by tkhle on 16.04.2024.
//

#ifndef GAME_PROGRAMMING_PATTERNS_EVENT_H
#define GAME_PROGRAMMING_PATTERNS_EVENT_H

enum Event {
    EVENT_ENTITY_FELL,
    EVENT_OTHER
};

#endif //GAME_PROGRAMMING_PATTERNS_EVENT_H
